source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxBluetoothKit_Example' do
  pod 'RxSwift', '2.4'
  pod 'RxBluetoothKit', :path => '../'
end

target 'RxBluetoothKit_Tests' do
  pod 'RxBluetoothKit', :path => '../'

  pod 'RxSwift', '2.4'
  pod 'RxTests', '2.4'
  pod 'Quick', '~> 0.9.1'
  pod 'Nimble', '3.2.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "RxTests"
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
            config.build_settings['ENABLE_TESTABILITY'] = 'YES'
        end
    end
end
