source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

target 'Example' do
  pod 'RxSwift'
  pod 'RxBluetoothKit', :git => 'https://github.com/Polidea/RxBluetoothKit.git', :branch => 'feature/sharing_problem_fix'
end

