github_url: https://github.com/Polidea/RxBluetoothKit
module: RxBluetoothKit
author_url: https://polidea.com
author: Polidea
swift_version: 4.0.3
clean: true
output: docs
root-url: https://polidea.github.io/RxBluetoothKit/

podspec: RxBluetoothKit.podspec
